name: todo_amplify
description: A new Flutter project.
publish_to: "none"
version: 0.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  amplify_core: ^0.1.1
  amplify_flutter: ^0.1.1
  amplify_auth_cognito: ^0.1.1
  amplify_datastore: ^0.1.1
  amplify_api: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
